import "@/styles/globals.css";
import type { Metadata } from "next";
import Sidebar from "@/components/ui/sidebar";
import Navbar from "./_components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  params: { locale },
  children,
}: {
  params: { locale: string };
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="absolute top-0 h-screen w-screen overflow-hidden">
        <div className="h-1/2 w-full bg-primary"></div>
      </div>
      {/* Main Layer */}
      <div className="absolute top-0 z-10 flex h-auto w-full">
        {/* Sidebar Layer */}
        <div className="fixed top-0 z-10 hidden h-full w-72 justify-center xl:relative xl:flex">
          <div className="fixed top-0 h-full w-64 py-2">
            <Sidebar locale={locale} />
          </div>
        </div>

        {/* Content Layer */}
        <div className="h-auto w-full px-2 py-2 lg:px-4 xl:w-[calc(100%-288px)]">
          {/* Navbar Layer */}
          <div className="h-auto w-full py-[18px]">
            <Navbar />
          </div>
          <div className="h-auto w-full">{children}</div>
        </div>
      </div>
    </>
  );
}
