import "@/styles/globals.css";
import { dir } from "i18next";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import Providers from "@/lib/react query/provider";
import { Toaster } from "react-hot-toast";
import { languages } from "../i18n/settings";

const vazirmatn = Vazirmatn({
  style: "normal",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return languages.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body
        className={`${vazirmatn.className} relative overflow-x-hidden bg-gray-100`}>
        <Providers>{children}</Providers>
        <Toaster
          position="top-center"
          gutter={12}
          containerStyle={{ margin: "8px" }}
          toastOptions={{
            success: {
              duration: 3000,
            },
            error: {
              duration: 5000,
            },
            style: {
              fontSize: "16px",
              maxWidth: "500px",
              padding: "16px 24px",
              direction: "rtl",
            },
          }}
        />
      </body>
    </html>
  );
}
